VALID_TOOLCHAINS := newlib pnacl

TARGET = moonlight-chrome

include $(NACL_SDK_ROOT)/tools/common.mk

# Include Moonlight-Common-C makefile
include common-c.mk

LIBS = ppapi pthread

CFLAGS = -Wall -Wno-missing-braces
SOURCES = \
    $(COMMON_C_SOURCE)       \
    libchelper.c             \

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

# The PNaCl workflow uses both an unstripped and finalized/stripped binary.
# On NaCl, only produce a stripped binary for Release configs (not Debug).
ifneq (,$(or $(findstring pnacl,$(TOOLCHAIN)),$(findstring Release,$(CONFIG))))
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
